#!/bin/bash

. /etc/log2zram.conf



isSafe () {
	[ -d $HDD_DIR/ ] || echo "ERROR: $HDD_DIR/ doesn't exist! Can't sync." 
	[ -d $HDD_DIR/ ] || exit 1
}

syncToDisk () {
	isSafe
	cp -arvfu $ZRAM_DIR -T $HDD_DIR
}

syncFromDisk () {
	isSafe
	getUsage
	DIR_SIZE=$(du -sk $HDD_DIR/ | awk '{ print $1 }')
	if [ "$BYTES_AVAIL" -lt "$DIR_SIZE" ];then
		echo "ERROR: RAM disk too small. Can't sync." 
			exit 1
	fi
	cp -arvf $HDD_DIR -T $ZRAM_DIR || exit 1
}



createZramLogDrive () {
	# Check Zram Class created
	if [ ! -d "/sys/class/zram-control" ]; then
		modprobe --verbose zram
		ZRAM_DEV='0'
	else
		ZRAM_DEV=$(cat /sys/class/zram-control/hot_add)
	fi
	echo ${COMP_ALG} > /sys/block/zram${ZRAM_DEV}/comp_algorithm
	echo ${DISK_SIZE} > /sys/block/zram${ZRAM_DEV}/disksize
	echo ${SIZE} > /sys/block/zram${ZRAM_DEV}/mem_limit
	mke2fs -v -t ext4 /dev/zram${ZRAM_DEV}
}

getUsage () {
	BYTES_AVAIL=$(df "/var/log" | tail -1 | awk '{ print $4 }')
	BYTES_USED=$(df "/var/log" | tail -1 | awk '{ print $3 }')
	
}


case "$1" in
	start)
		if [ ! -z "$ZRAM_DIR" ]
		then
			mount --verbose --bind $ZRAM_DIR/ $HDD_DIR/
			mount --verbose --make-private $HDD_DIR/
			createZramLogDrive
			mount --verbose --types ext4 -o nosuid,noexec,nodev /dev/zram${ZRAM_DEV} ${ZRAM_DIR}/
			sync
			syncFromDisk
		else
			echo 'No working ZRAM_DIR in zramdrive.conf'
			exit 1
		fi
		;;

	stop)
		syncToDisk
		umount -l $ZRAM_DIR/
		umount -l $HDD_DIR/
		;;

	*)
		echo "Usage: log2ram {start|stop|write}" >&2
		exit 1
	;;
esac
