#!/bin/bash

. /etc/zramdrive.conf

ZSHARE=/usr/local/share/zramdrive
ZLOG=${ZSHARE}/log/zramdrive.log


createZramDrive () {
	# Check Zram Class created
	if modprobe --verbose --first-time zram  >>${ZLOG} 2>&1 
	then
		DEV_NUM='0'
	else
		DEV_NUM=$(cat /sys/class/zram-control/hot_add)
	fi
	echo ${COMP_ALG} > /sys/block/zram${DEV_NUM}/comp_algorithm
	echo ${DISK_SIZE} > /sys/block/zram${DEV_NUM}/disksize
	echo ${SIZE} > /sys/block/zram${DEV_NUM}/mem_limit
	mke2fs -v -t ext4 $MKFS_OPTS /dev/zram${DEV_NUM} >>${ZLOG} 2>&1 || return 1
}

mergeOverlay () {
	echo "overlay lowerdir=${HDD_DIR},upperdir=${ZDIR}/zram${DEV_NUM}/upper" >>${ZLOG}
	cd /usr/local/lib/zramdrive/
	./overlay merge -l "${HDD_DIR}" -u "${ZDIR}/zram${DEV_NUM}/upper" >>${ZLOG} 2>&1 || return 1
	sh -x *.sh  >>${ZLOG} 2>&1 || return 1
	rm -v *.sh  >>${ZLOG} 2>&1 || return 1
	
}

case "$1" in
	start)
		echo "zramdrive start $(date +%Y-%m-%d-%H:%M:%S)" >>${ZLOG}
		mkdir -p $HDD_DIR  >>${ZLOG} 2>&1 || exit 1
		mount --verbose --bind $ZRAM_DIR/ $HDD_DIR/ >>${ZLOG} 2>&1 || exit 1
		mount --verbose --make-private $HDD_DIR/ >>${ZLOG} 2>&1 || exit 1
		createZramDrive >>${ZLOG} 2>&1 || exit 1
		mkdir -vp ${ZDIR}/zram${DEV_NUM} >>${ZLOG} 2>&1 || exit 1
		mount --verbose --types ext4 $MNT_OPTS /dev/zram${DEV_NUM} ${ZDIR}/zram${DEV_NUM}/ >>${ZLOG} 2>&1 || exit 1
		mkdir -vp ${ZDIR}/zram${DEV_NUM}/upper ${ZDIR}/zram${DEV_NUM}/workdir ${ZRAM_LOG} >>${ZLOG} 2>&1 || exit 1
		mount --verbose --types overlay -o redirect_dir=off,lowerdir=${HDD_DIR},upperdir=${ZDIR}/zram${DEV_NUM}/upper,workdir=${ZDIR}/zram${DEV_NUM}/workdir overlay${DEV_NUM} ${ZRAM_DIR} >>${ZLOG} 2>&1 || exit 1
		echo "/zram${DEV_NUM}" > ${ZSHARE}/zram-device-list
		;;

	stop)
		echo "zramdrive stop $(date +%Y-%m-%d-%H:%M:%S)" >>${ZLOG}
		ZRAM_DEV=$(cat ${ZSHARE}/zram-device-list)
		DEV_NUM=$(echo "$ZRAM_DEV" | tr -dc '0-9')
		if umount --verbose ${ZRAM_DIR}/ >>${ZLOG} 2>&1
		then
			echo "umount ${ZRAM_DIR}/" >>${ZLOG}
		else
		sleep .1
			umount --verbose -l ${ZRAM_DIR}/ >>${ZLOG} 2>&1 
		fi
		mergeOverlay >>${ZLOG} 2>&1
		if umount --verbose ${ZDIR}${ZRAM_DEV}/ >>${ZLOG} 2>&1
		then
			echo "umount ${ZDIR}{ZRAM_DEV}/" >>${ZLOG}
		else
			umount --verbose -l ${ZDIR}{ZRAM_DEV}/ >>${ZLOG} 2>&1 
		fi
		if umount --verbose $HDD_DIR/ >>${ZLOG} 2>&1
		then
			echo "umount $HDD_DIR/" >>${ZLOG}
		else
			sleep .1
			umount --verbose -l $HDD_DIR/ >>${ZLOG} 2>&1
		fi
		if [ "$DEV_NUM" = "0" ]
		then
			rmmod zram
		else
			echo "$DEV_NUM" > /sys/class/zram-control/hot_remove
		fi
		;;

	*)
		echo "Usage: zramdrive {start|stop}" >&2
		exit 1
		
esac

